# Generated by Django 5.1.4 on 2025-06-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
