# Generated by Django 5.1.4 on 2025-06-18 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budget_user_budget_description'),
        ('wallet', '0003_wallet_expired_date_alter_wallet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='wallet',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
    ]
