# Generated by Django 5.1.4 on 2025-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budget_name_alter_budget_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
