# Generated by Django 5.1.4 on 2025-06-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_budget_name'),
        ('category', '0001_initial'),
        ('wallet', '0004_alter_wallet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='wallet',
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='wallet',
            field=models.ManyToManyField(to='wallet.wallet'),
        ),
    ]
