services:
  - type: web
    name: django-ninja-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn mymoney.asgi:application --host 0.0.0.0 --port 8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mymoney.settings
      - key: ALLOWED_HOSTS
        value: yourdomain.com