# Generated by Django 5.1.4 on 2025-01-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saving',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
