# Generated by Django 5.1.4 on 2025-10-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('USING', 'USING'), ('USED', 'USED'), ('LOSS', 'LOSS'), ('BROKEN', 'BROKEN'), ('NOT_USE', 'NOT_USE'), ('GIVE', 'GIVE')], default='USING', max_length=20)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('buy_date', models.DateField()),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
