# Generated by Django 5.1.4 on 2025-10-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='buy_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sell_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
