# Generated by Django 5.1.4 on 2025-11-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_asset_buy_date_alter_asset_sell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
