# Generated by Django 5.1.4 on 2025-01-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('transaction', '0004_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.budget'),
        ),
    ]
