# Generated by Django 5.1.4 on 2025-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('CASH', 'cash'), ('BANK', 'bank'), ('SAVINGS', 'savings')], max_length=50),
        ),
    ]
