# Generated by Django 5.1.4 on 2025-06-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK'), ('SAVING', 'SAVING')], max_length=50),
        ),
    ]
