# Generated by Django 5.1.4 on 2025-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_expired_date_alter_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK'), ('SAVING', 'SAVING'), ('BUDGET', 'BUDGET')], max_length=50),
        ),
    ]
